import { memo } from 'react';
import { BranchIcon, PencilIcon, RefreshIcon } from '@/components/icons';
import { formatRelativeTime } from '@/lib/dates';
import { formatCost, formatNumber } from '@/lib/numbers';
import type { Message } from '@/types/chat';
import { CopyButton } from './copy-button';
import { VariantSwitcher } from './variant-switcher';

function UsageBadge({ message }: { message: Message }) {
    const tokens = message.usage
        ? (message.usage.prompt_tokens ?? 0) +
          (message.usage.completion_tokens ?? 0)
        : 0;

    if (tokens === 0 && message.cost === null) {
        return null;
    }

    const parts: string[] = [];

    if (tokens > 0) {
        parts.push(`${formatNumber(tokens)} tokens`);
    }

    if (typeof message.cost === 'number') {
        parts.push(formatCost(message.cost));
    }

    const tooltip = message.usage
        ? `${formatNumber(message.usage.prompt_tokens ?? 0)} prompt + ${formatNumber(
              message.usage.completion_tokens ?? 0,
          )} completion`
        : undefined;

    return (
        <span
            className="px-1 text-xs text-gray-400 dark:text-gray-500"
            title={tooltip}
        >
            {parts.join(' · ')}
        </span>
    );
}

function MessageTimestamp({ iso }: { iso: string }) {
    const absolute = new Date(iso).toLocaleString();

    return (
        <span
            className="px-1 text-xs text-gray-400 dark:text-gray-500"
            title={absolute}
        >
            {formatRelativeTime(iso)}
        </span>
    );
}

type Props = {
    message: Message;
    isLastAssistant: boolean;
    isEditing: boolean;
    variantIndex?: number;
    variantCount?: number;
    onSelectVariant?: (id: string | number, index: number) => void;
    onStartEdit: (messageId: string | number) => void;
    onBranchFromMessage: (id: string | number) => void;
    onRegenerate: () => void;
};

function MessageActionsImpl({
    message,
    isLastAssistant,
    isEditing,
    variantIndex,
    variantCount,
    onSelectVariant,
    onStartEdit,
    onBranchFromMessage,
    onRegenerate,
}: Props) {
    return (
        <div
            className={`mt-1 flex items-center gap-1 opacity-0 transition-opacity group-hover/msg:opacity-100 print:hidden ${
                message.role === 'user' ? 'justify-end' : ''
            }`}
        >
            {message.created_at && (
                <MessageTimestamp iso={message.created_at} />
            )}
            {message.role === 'assistant' &&
                variantCount !== undefined &&
                variantCount > 1 &&
                variantIndex !== undefined &&
                onSelectVariant && (
                    <VariantSwitcher
                        messageId={message.id}
                        index={variantIndex}
                        total={variantCount}
                        onSelect={onSelectVariant}
                    />
                )}
            {message.role === 'assistant' && message.model && (
                <span
                    className="px-1 text-xs text-gray-400 dark:text-gray-500"
                    title={`Generated by ${message.model}`}
                >
                    {message.model}
                </span>
            )}
            {message.role === 'assistant' && <UsageBadge message={message} />}
            <CopyButton content={message.content} />
            {message.role === 'user' &&
                !isEditing &&
                typeof message.id === 'string' && (
                    <button
                        type="button"
                        onClick={() => onStartEdit(message.id)}
                        className="rounded p-1 text-gray-400 transition-colors hover:text-gray-600 dark:text-gray-500 dark:hover:text-gray-300"
                        aria-label="Edit message"
                    >
                        <PencilIcon />
                    </button>
                )}
            {typeof message.id === 'string' && !isEditing && (
                <button
                    type="button"
                    onClick={() => onBranchFromMessage(message.id)}
                    className="rounded p-1 text-gray-400 transition-colors hover:text-gray-600 dark:text-gray-500 dark:hover:text-gray-300"
                    aria-label="Branch from here"
                    title="Branch from here"
                >
                    <BranchIcon />
                </button>
            )}
            {isLastAssistant && (
                <button
                    type="button"
                    onClick={onRegenerate}
                    className="rounded p-1 text-gray-400 transition-colors hover:text-gray-600 dark:text-gray-500 dark:hover:text-gray-300"
                    aria-label="Regenerate response"
                >
                    <RefreshIcon />
                </button>
            )}
        </div>
    );
}

/**
 * Memoized so the action row skips re-rendering during streaming for
 * any message whose data and handlers haven't changed. The parent must
 * pass stable callbacks (e.g. via useCallback) for this to matter.
 */
export const MessageActions = memo(MessageActionsImpl);
